Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.15.100"

  config.vm.hostname = "world1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "1"
    vb.name = "World2017DemoVM1"
  end

$script = <<SCRIPT
echo "Provisioning..."
date > /etc/vagrant_provisioned_at

sudo apt-get -qq update
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list

sudo apt-get -qq update
sudo apt-get -qq install -y --force-yes mongodb-org mysql-client zip

echo "Creating Databases ..."
mongoimport -d owners -c people /vagrant/DATA/people.json
mongoimport -d owners -c cars /vagrant/DATA/cars.json

echo "Decompressing and Installing BI Connector"
mkdir /home/vagrant/connector_v2
pushd /home/vagrant/connector_v2
wget https://info-mongodb-com.s3.amazonaws.com/mongodb-bi/v2/mongodb-bi-linux-x86_64-ubuntu1404-v2.1.0.tgz -nv
tar -xf mongodb-bi-linux-x86_64-ubuntu1404-v2.1.0.tgz
popd

sudo chown -R vagrant:vagrant /home/vagrant/connector_v2

export PATH=/home/vagrant/connector_v2/mongodb-bi-linux-x86_64-ubuntu1404-v2.1.0/bin:$PATH
echo "export PATH=/home/vagrant/connector_v2/mongodb-bi-linux-x86_64-ubuntu1404-v2.1.0/bin:$PATH" >> .bashrc

echo "Creating DRDL files ..."
mkdir /home/vagrant/schema

echo "mongodrdl -d owners -c people -o schema/people.drdl" > genpeople.sh
echo "mongodrdl -d owners -c cars -o schema/cars.drdl" > gencars.sh

chmod +x genpeople.sh
chmod +x gencars.sh

./genpeople.sh

sudo chown -R vagrant:vagrant /home/vagrant/schema

echo "Setting up mongosqld script"

echo "mongosqld --schemaDirectory=/home/vagrant/schema --addr=0.0.0.0:3307 -vv" > startmongosqld.sh
chmod +x startmongosqld.sh

echo "mysql --host=localhost --port=3307 --protocol=tcp" > mysql.sh
chmod +x mysql.sh

echo "Restarting mongod"
sudo service mongod stop
sudo sed -i "s/.*bindIp.*/  bindIp: 0.0.0.0/" /etc/mongod.conf
sudo service mongod start

sudo chown -R vagrant:vagrant /home/vagrant

SCRIPT
config.vm.provision "shell", inline: $script

end
